apiVersion: v1
kind: Service
metadata:
  name: cassandra
spec:
  selector:
    app: cassandra
  ports:
    - protocol: TCP
      port: 9042
      targetPort: 9042
---
apiVersion: v1
kind: Service
metadata:
  name: cassandra-headless
spec:
  selector:
    app: cassandra
  clusterIP: None
  ports:
    - protocol: TCP
      port: 9042
      targetPort: 9042
