apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cassandra-statefulset
spec:
  serviceName: cassandra-headless
  replicas: 3
  selector:
    matchLabels:
      app: cassandra
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      containers:
        - name: cassandra
          image: my-cassandra-image:latest
          ports:
            - containerPort: 9042
          env:
            - name: CASSANDRA_SEEDS
              value: "cassandra-statefulset-0.cassandra-headless.default.svc.cluster.local"
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1"
  volumeClaimTemplates:
    - metadata:
        name: cassandra-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: cassandra
spec:
  selector:
    app: cassandra
  ports:
    - protocol: TCP
      port: 9042
      targetPort: 9042
---
apiVersion: v1
kind: Service
metadata:
  name: cassandra-headless
spec:
  selector:
    app: cassandra
  clusterIP: None
  ports:
    - protocol: TCP
      port: 9042
      targetPort: 9042
